name: Annotation
on: workflow_dispatch
jobs:
  log:
   runs-on: ubuntu-latest
   steps:
    - run: echo "::error::This is an error"
    - run: echo "::warn::This is a warn"
    - run: echo "::notice::This is a notice"
          