name: Cache
on: workflow_dispatch
jobs:
  cache:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@4
    - uses: actions/cache@v4 # キャッシュの復元と保存
      with:
       key: test-${{ runner.os }}-${{ github.sha }} # キャッシュキー
       path: ${{ github.workspace }}/dummy # キャッシュ対象のパス
       restore-keys: | # リストアキー
         test-${{ runner.os }}-
    - run: | # 既にキャッシュが存在していれば復元。なければダミーファイル生成
        if [[ -f "${GITHUB_WORKSPACE}/dummy" ]]; then exit 0; fi
        dd if=/dev/urandom of="${GITHUB_WORKSPACE}/dummy" bs=1M count=10
        sleep 30
    - run: ls -lh "${GITHUB_WORKSPACE}/dummy"
