name: Manual
on:
  workflow_dispatch: # 手動実行イベント
    inputs:
     greeting:
      type: string
      default: Hello
      required: true
     log-leve:
       type: choice
       options:
         - info
         - warn
         - error
jobs:
  run:
   runs-on: ubuntu-latest
   steps:
    - run: echo "${{ inputs.greeting }}"